title: Your awesome title
author:
  name: Palt0n
  github: https://github.com/Palt0n
description: > # this means to ignore newlines until "show_excerpts:"
  When not automating things at work, I automate things at home. As a
  tinkerer, I enjoy electronics design, 3D printing and managing my
  home lab; Which is all second only to my love for coding in Python.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

  # generate social links in footer
  social_links:
    - { platform: github,         user_url: "https://github.com/palt0n/" }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/10693679/palton" }
    - { platform: reddit,        user_url: "https://www.reddit.com/user/Palton01" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
